articles/urls.py
from django.urls import path

from .views import (
    article_search_view,
    article_create_view,
    article_detail_view
)

app_name = 'articles'
urlpatterns = [
    path('', article_search_view, name='search'),
    path('create/', article_create_view, name='create'),
    path('<slug:slug>/', article_detail_view, name='detail'),
]

main/urls.py
from django.contrib import admin
from django.urls import include, path, re_path

from accounts.views import (
    login_view,
    logout_view,
    register_view
)

from meals.views import meal_queue_toggle_view

from search.views import search_view
from .views import home_view

urlpatterns = [
    path('', home_view), # index / home / root 
    path('pantry/recipes/', include('recipes.urls')),
    path('articles/', include('articles.urls')),
    path('meal-toggle/<int:recipe_id>/', meal_queue_toggle_view, name='meal-toggle'),
    path('search/', search_view, name='search'),
    path('admin/', admin.site.urls),
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
         <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

          <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">


        <script src="https://unpkg.com/htmx.org@1.5.0"></script>
        <link rel='stylesheet' href='{% static "recipes/recipes-htmx.css" %}' />
    </head>
    <body>
        {% include 'base/navbar.html' %}
        
        <div class='container'>
            
            {% block content %}
            <h3>This will be replaced</h3>
            {% endblock content %}
        </div>

        
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

        <script>
            document.body.addEventListener("htmx:configRequest", (event)=>{
                event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}'
            })
        </script>
    </body>
</html>

templates/home-view.html
{% extends "base.html" %}

{% block content %}
<h1>{{ object.title }} (id: {{ id }})!</h1>
<p>{{ content }}!</p>

<a href='{% url "articles:create" %}'>Create Article</a>
<a href='{% url "articles:detail" slug="hello-world" %}'>Hello world article</a>
<ul>
    {% for x in object_list %}
        {% if x.title %}
            <li><a href='{{ x.get_absolute_url }}'>{{ x.title }} - {{ x.content }}</a></li>
        {% endif %}
    {% endfor %}
</ul>

{% endblock content %}

templates/image-form.html
{% extends "base.html" %}


{% block content %}

<form action='.' method="POST" enctype="multipart/form-data"
    hx-post="{{ request.path }}"
    hx-encoding="multipart/form-data"

>
    {% csrf_token %}
    {{ form.as_p }}
    <button style='margin-top:10px;' type='submit' >Upload Image</button>
</form>

{% endblock content %}